[package]
name = "bose_hubbard"
version = "0.1.0"
edition = "2018"

[dependencies]
nalgebra = '0.32.2'
rayon = "1.7.0"
serde = { version = "1.0.163", features = ["derive"] }
serde_yaml = "0.9.21"
itertools-num = "0.1.3"
